EIP-4844 Experimental Support
MariusVanDerWijden/tx-fuzz pull request #7
Opened 2022-10-21 00:07 UTC by rauljordan

This PR adds some experimental support for 4844 txs by using the latest commit of https://github.com/mdehoog/go-ethereum

2022-10-22 13:06 UTC, MariusVanDerWijden reviewed
Two small nits, looks very good thank you for your contribution

2022-10-22 13:06 UTC, MariusVanDerWijden commented on transactions.go
> +			BlobVersionedHashes: versionedHashes,
Could you also add some data pls? I am going to modify fuzzyVM (which creates the tx data) to also create calls to the blob precompile as well as the datahash opcode

2022-10-22 13:06 UTC, MariusVanDerWijden commented on transactions.go
> +		al, err := CreateAccessList(rpc, tx, sender)
Would be nice to also have a version without al, since some clients still don't support creating an al, so they would not send blob txs

2022-10-23 21:32 UTC, 0xGabi requested changes
Thank you for adding 4844 support. I left a small review.

2022-10-23 21:32 UTC, 0xGabi commented on transactions.go
> +		panic("fee cap not big int")
```suggestion
		panic("value not big int")
```

2022-10-23 21:32 UTC, 0xGabi commented on transactions.go
> +		Message: types.BlobTxMessage{
Comparing with https://github.com/Inphi/blob-utils/blob/master/main.go#L125-L136 I think we are missing `ChainID` and  `MaxFeePerDataGas`.

2022-10-24 03:17 UTC, rauljordan commented
Hi @MariusVanDerWijden and @0xGabi thanks for the review. I have added the requested fields and random data. One question I had was how big should the max data size be per transaction for the purpose of this PR. I know the total we are aiming for in a single block is definitely < 1Mb, probably closer to 256-512Kb. I added a randomBlobData func which generates data to be encoded into a blob of random size from 0 to 512Kb. Let me know if this is unreasonable, as we might be creating a single tx with 512Kb worth of data being encoded into a blob (is that even allowed)?

2022-10-25 10:59 UTC, closed without merging

2022-10-25 11:03 UTC, MariusVanDerWijden commented
Hey I fucked up a bit with git. I force pushed some weird old stuff onto your branch which overwrote all your changes.
I rescued your commit to another branch now

2022-10-25 11:05 UTC, MariusVanDerWijden commented
It's here: https://github.com/MariusVanDerWijden/tx-fuzz/pull/8
The problem is that I can't reopen your PR :( but your commit history with attribution is preserved on the other branch as well.
Again sorry about that

2022-10-25 14:26 UTC, rauljordan commented
@MariusVanDerWijden ha no worries about it - it's happened to me as well 😆. Was happy to make this small contribution to save you some time